server:
  port: 9080
spring:
  application:
    name:
      trip-service
  jpa:
    generate-ddl: true
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.hibernate.SQL: DEBUG
    io.eventuate: DEBUG
    io.examples: DEBUG