apiVersion: v1
kind: Service
metadata:
  name: petstore
  labels:
    app: petstore
spec:
  type: NodePort
  selector:
    app: petstore
  ports:
  - protocol: TCP
    port: 9080
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: petstore
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: petstore
    spec:
      containers:
      - name: petstore
        image: garycheng/petstore:1.0
        ports:
        - containerPort: 9080