#Application configuration
server:
  port: 9080

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 125MB

file:
  upload-dir: c:/tmp/files/uploads

logging:
  level:
    io.examples: DEBUG